name: Build NetHunter Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Build with dabao1955's Kernel Builder
        uses: dabao1955/kernel_build_action@main
        with:
          # Kernel source
          kernel-url: https://github.com/Anmol6002/kernel_source_sm-x115
          kernel-branch: main
          config: gta9_defconfig
          arch: arm64

          # Toolchains
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r383902

          # NetHunter features (LXC enabled, but patching disabled to avoid 5.10 conflicts)
          lxc: true
          lxc-patch: false      # optional, can test true later
          nethunter: true
          nethunter-patch: false

          # Optimization
          ccache: true
          disable-lto: false

          # Packaging and release
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
